[build]
  publish = "master-dist"

[[redirects]]
from = "/clock/*"
to = "/master-dist/Clock/index.html"
status = 200

[[redirects]]
from = "/drum-machine/*"
to = "/master-dist/Drum-machine/index.html"
status = 200

[[redirects]]
from = "/js-calculator/*"
to = "/master-dist/Js-calculator/index.html"
status = 200

[[redirects]]
from = "/markdown-previewer/*"
to = "/master-dist/Markdown-previewer/index.html"
status = 200

[[redirects]]
from = "/random-quote-machine/*"
to = "/master-dist/Random-quote-machine/index.html"
status = 200
