[build]
  publish = "master-dist"
  command = """
    cd Clock && pnpm install && pnpm run build && cd ..
    cd Drum-machine && pnpm install && pnpm run build && cd ..
    cd Js-calculator && pnpm install && pnpm run build && cd ..
    cd Markdown-previewer && pnpm install && pnpm run build && cd ..
    cd Random-quote-machine && pnpm install && pnpm run build && cd ..
    mkdir -p master-dist/Clock && mv Clock/dist/* master-dist/Clock/ &&
    mkdir -p master-dist/Drum-machine && mv Drum-machine/dist/* master-dist/Drum-machine/ &&
    mkdir -p master-dist/Js-calculator && mv Js-calculator/dist/* master-dist/Js-calculator/ &&
    mkdir -p master-dist/Markdown-previewer && mv Markdown-previewer/dist/* master-dist/Markdown-previewer/ &&
    mkdir -p master-dist/Random-quote-machine && mv Random-quote-machine/dist/* master-dist/Random-quote-machine/
  """

[[redirects]]
from = "/clock/*"
to = "/master-dist/Clock/index.html"
status = 200

[[redirects]]
from = "/drum-machine/*"
to = "/master-dist/Drum-machine/index.html"
status = 200

[[redirects]]
from = "/js-calculator/*"
to = "/master-dist/Js-calculator/index.html"
status = 200

[[redirects]]
from = "/markdown-previewer/*"
to = "/master-dist/Markdown-previewer/index.html"
status = 200

[[redirects]]
from = "/random-quote-machine/*"
to = "/master-dist/Random-quote-machine/index.html"
status = 200
